# Generated by Django 4.1 on 2023-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
