# Generated by Django 4.1 on 2023-04-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_recommendation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=3000)),
                ("category", models.CharField(max_length=30)),
                ("difficuly_rating", models.CharField(max_length=30)),
                ("course_url", models.CharField(max_length=3000)),
                ("course_description", models.TextField(max_length=5000)),
            ],
        ),
    ]
