# Generated by Django 4.1 on 2023-03-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_recommendation", "0002_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
